//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaOcenki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        public int StudentId { get; set; }
        public string StudentIme { get; set; }
        public string StudentPrezime { get; set; }
        public string StudentIndex { get; set; }
        public string PredmetIme { get; set; }
        public string Ocena { get; set; }
        public string RedovnostPoeni { get; set; }
        public string KolokviumPrvPoeni { get; set; }
        public string KolokviumVtorPoeni { get; set; }
        public string IspitPoeni { get; set; }
    }
}
