//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacijaOcenki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int LoginId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string ProfIme { get; set; }
        public string ProfPrezime { get; set; }
        public string PredmetIme { get; set; }
    }
}
